### ISSUE TITLE
Apache spark not working

### ISSUE THREAD

**Issue by lohithcode** [krisgeus/ansible_local_cdh_hadoop#2]
Getting error when trying to run 'spark-shell'
"ls: cannot access /opt/cdh5/spark-1.2.0-cdh5.3.0/assembly/target/scala-2.10: No such file or directory
Failed to find Spark assembly in /opt/cdh5/spark-1.2.0-cdh5.3.0/assembly/target/scala-2.10
You need to build Spark before running this program."

there was discussion at http://qnalist.com/questions/5576270/spark-binaries-for-cdh

This tarball is not built seems like cloudera changed the distribution. Any ideas to get it work ?
tarball downloaded: spark-1.2.0-cdh5.3.0.tar.gz

**Comment by krisgeus** [comment]
Hi.

To make it work here are the differences between the downloaded tarball and my local working directory:

diff -r spark-1.2.0-cdh5.3.0 ../spark-1.2.0-cdh5.3.0
Only in ../spark-1.2.0-cdh5.3.0: RELEASE
diff -r spark-1.2.0-cdh5.3.0/bin/compute-classpath.sh ../spark-1.2.0-cdh5.3.0/bin/compute-classpath.sh
66c66,67

## <   assembly_folder="$FWDIR"/lib

>   #assembly_folder="$FWDIR"/lib
>   assembly_folder="$FWDIR"/
> 98a100,110
> 
> # Adding hadoop classpath references here'
> 
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/common/_:$HADOOP_PREFIX/share/hadoop/common/lib/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/mapreduce/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/mapreduce/lib/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/yarn/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/yarn/lib/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/hdfs/_"
> CLASSPATH="$CLASSPATH:$HADOOP_PREFIX/share/hadoop/hdfs/lib/_"
> CLASSPATH="$CLASSPATH:$HIVE_HOME/lib/_"
> CLASSPATH="$CLASSPATH:$SPARK_HOME/lib/_"

(the ../spark... is the working one)
In the spark/tasks/main.yml there were tasks to do this for you but i commented them to see if the new release already fixed this. 

Apparently not.
PR is welcome if you can test if the original changes still work

**Comment by lohithcode** [comment]
I made changes to ../spark-1.2.0-cdh5.3.0/bin/compute-classpath.sh, however still getting same error.
Also tried uncommenting  following the spark/tasks/main.yml  tasks  and running again but still no avail.
- name: Add hadoop stuff to spark classpath (for spark 1.1)
  and 
  - name: Fix bug in classpath (for spark 1.1)

error:
ls: /opt/cdh5/spark-1.2.0-cdh5.3.0/assembly/target/scala-2.10: No such file or directory
Failed to find Spark assembly in /opt/cdh5/spark-1.2.0-cdh5.3.0/assembly/target/scala-2.10
You need to build Spark before running this program.

**Comment by lohithcode** [comment]
I got it working now.
 I removed the  task [- name: Fix bug in classpath (for spark 0.9)] and ran again.
